name: "Build mCoder Windows"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Stable pour tes dépendances natives
          cache: 'npm'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          npm install
          # VS Code a besoin de gulp en global souvent pour ses scripts de build
          npm install -g gulp

      - name: Compile mCoder
        run: |
          npm run gulp compile
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Build Windows Executable
        run: |
          # C'est la commande de VS Code pour packager l'archive Windows
          npm run gulp vscode-win32-x64-archive 
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mCoder-Windows
          path: ../vscode-rebuild-x64 # Le dossier de sortie par défaut de VS Code
